version: '3.9'

services:
  michoacana_db:
    restart: always
    container_name: michoacana_db
    image: postgres:15.8
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./postgres:/var/lib/postgres/data


